### ISSUE TITLE
Lỗi khi xóa hàng

### ISSUE THREAD

**Issue by LTBach** [Chirox03/Tetrix#34]
Lỗi màu các thành viên liên quan chú ý @lltlien @21520800

**Comment by LTBach** [comment]
- [
![Screenshot (310)](https://user-images.githubusercontent.com/96047328/148784187-bd7d75d2-d1a1-46fa-a8b7-72e1a65d5bd2.png)
](url)

**Comment by 21520800** [comment]
sửa rồi mà nhỉ @@
